# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSanalysis.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IDLS_analyzer_dpss(object):
    def setupUi(self, IDLS_analyzer_dpss):
        IDLS_analyzer_dpss.setObjectName("IDLS_analyzer_dpss")
        IDLS_analyzer_dpss.resize(1009, 778)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IDLS_analyzer_dpss.sizePolicy().hasHeightForWidth())
        IDLS_analyzer_dpss.setSizePolicy(sizePolicy)
        IDLS_analyzer_dpss.setMinimumSize(QtCore.QSize(0, 0))
        IDLS_analyzer_dpss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(IDLS_analyzer_dpss)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_back.sizePolicy().hasHeightForWidth())
        self.pushButton_back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_4.addWidget(self.pushButton_back)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.listWidget_fit = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_fit.sizePolicy().hasHeightForWidth())
        self.listWidget_fit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.listWidget_fit.setFont(font)
        self.listWidget_fit.setObjectName("listWidget_fit")
        self.verticalLayout_2.addWidget(self.listWidget_fit)
        self.pushButton_set2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set2.sizePolicy().hasHeightForWidth())
        self.pushButton_set2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_set2.setFont(font)
        self.pushButton_set2.setObjectName("pushButton_set2")
        self.verticalLayout_2.addWidget(self.pushButton_set2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_plotopt2 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_plotopt2.sizePolicy().hasHeightForWidth())
        self.comboBox_plotopt2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.comboBox_plotopt2.setFont(font)
        self.comboBox_plotopt2.setObjectName("comboBox_plotopt2")
        self.comboBox_plotopt2.addItem("")
        self.comboBox_plotopt2.addItem("")
        self.comboBox_plotopt2.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_plotopt2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_fitini2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fitini2.sizePolicy().hasHeightForWidth())
        self.lineEdit_fitini2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_fitini2.setFont(font)
        self.lineEdit_fitini2.setObjectName("lineEdit_fitini2")
        self.horizontalLayout_6.addWidget(self.lineEdit_fitini2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.pushButton_dpss = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dpss.sizePolicy().hasHeightForWidth())
        self.pushButton_dpss.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_dpss.setFont(font)
        self.pushButton_dpss.setObjectName("pushButton_dpss")
        self.gridLayout_2.addWidget(self.pushButton_dpss, 4, 1, 1, 1)
        self.listWidget_fitres = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_fitres.sizePolicy().hasHeightForWidth())
        self.listWidget_fitres.setSizePolicy(sizePolicy)
        self.listWidget_fitres.setObjectName("listWidget_fitres")
        self.gridLayout_2.addWidget(self.listWidget_fitres, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 1, 1, 1)
        self.pushButton_delfitres = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delfitres.sizePolicy().hasHeightForWidth())
        self.pushButton_delfitres.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_delfitres.setFont(font)
        self.pushButton_delfitres.setObjectName("pushButton_delfitres")
        self.gridLayout_2.addWidget(self.pushButton_delfitres, 3, 1, 1, 1)
        self.radioButton_ind = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ind.sizePolicy().hasHeightForWidth())
        self.radioButton_ind.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.radioButton_ind.setFont(font)
        self.radioButton_ind.setChecked(True)
        self.radioButton_ind.setObjectName("radioButton_ind")
        self.gridLayout_2.addWidget(self.radioButton_ind, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_fitini1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fitini1.sizePolicy().hasHeightForWidth())
        self.lineEdit_fitini1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_fitini1.setFont(font)
        self.lineEdit_fitini1.setObjectName("lineEdit_fitini1")
        self.horizontalLayout.addWidget(self.lineEdit_fitini1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_onefit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_onefit.sizePolicy().hasHeightForWidth())
        self.pushButton_onefit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_onefit.setFont(font)
        self.pushButton_onefit.setObjectName("pushButton_onefit")
        self.verticalLayout_7.addWidget(self.pushButton_onefit)
        self.pushButton_twofit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_twofit.sizePolicy().hasHeightForWidth())
        self.pushButton_twofit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_twofit.setFont(font)
        self.pushButton_twofit.setObjectName("pushButton_twofit")
        self.verticalLayout_7.addWidget(self.pushButton_twofit)
        self.pushButton_twolevelsfit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_twolevelsfit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_twolevelsfit.sizePolicy().hasHeightForWidth())
        self.pushButton_twolevelsfit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_twolevelsfit.setFont(font)
        self.pushButton_twolevelsfit.setObjectName("pushButton_twolevelsfit")
        self.verticalLayout_7.addWidget(self.pushButton_twolevelsfit)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.pushButton_acceptfit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_acceptfit.sizePolicy().hasHeightForWidth())
        self.pushButton_acceptfit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_acceptfit.setFont(font)
        self.pushButton_acceptfit.setObjectName("pushButton_acceptfit")
        self.verticalLayout_3.addWidget(self.pushButton_acceptfit)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.radioButton_simu = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_simu.sizePolicy().hasHeightForWidth())
        self.radioButton_simu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.radioButton_simu.setFont(font)
        self.radioButton_simu.setObjectName("radioButton_simu")
        self.verticalLayout_3.addWidget(self.radioButton_simu)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_Etlb = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Etlb.sizePolicy().hasHeightForWidth())
        self.lineEdit_Etlb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_Etlb.setFont(font)
        self.lineEdit_Etlb.setObjectName("lineEdit_Etlb")
        self.gridLayout.addWidget(self.lineEdit_Etlb, 3, 0, 1, 1)
        self.lineEdit_klb = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_klb.sizePolicy().hasHeightForWidth())
        self.lineEdit_klb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_klb.setFont(font)
        self.lineEdit_klb.setObjectName("lineEdit_klb")
        self.gridLayout.addWidget(self.lineEdit_klb, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.lineEdit_dk = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dk.sizePolicy().hasHeightForWidth())
        self.lineEdit_dk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_dk.setFont(font)
        self.lineEdit_dk.setObjectName("lineEdit_dk")
        self.gridLayout.addWidget(self.lineEdit_dk, 6, 2, 1, 1)
        self.lineEdit_kup = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_kup.sizePolicy().hasHeightForWidth())
        self.lineEdit_kup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_kup.setFont(font)
        self.lineEdit_kup.setObjectName("lineEdit_kup")
        self.gridLayout.addWidget(self.lineEdit_kup, 6, 1, 1, 1)
        self.lineEdit_dEt = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dEt.sizePolicy().hasHeightForWidth())
        self.lineEdit_dEt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_dEt.setFont(font)
        self.lineEdit_dEt.setObjectName("lineEdit_dEt")
        self.gridLayout.addWidget(self.lineEdit_dEt, 3, 2, 1, 1)
        self.lineEdit_Etub = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Etub.sizePolicy().hasHeightForWidth())
        self.lineEdit_Etub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_Etub.setFont(font)
        self.lineEdit_Etub.setObjectName("lineEdit_Etub")
        self.gridLayout.addWidget(self.lineEdit_Etub, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_sametaum = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_sametaum.sizePolicy().hasHeightForWidth())
        self.checkBox_sametaum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.checkBox_sametaum.setFont(font)
        self.checkBox_sametaum.setChecked(True)
        self.checkBox_sametaum.setObjectName("checkBox_sametaum")
        self.horizontalLayout_8.addWidget(self.checkBox_sametaum)
        self.pushButton_simufit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_simufit.sizePolicy().hasHeightForWidth())
        self.pushButton_simufit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_simufit.setFont(font)
        self.pushButton_simufit.setObjectName("pushButton_simufit")
        self.horizontalLayout_8.addWidget(self.pushButton_simufit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_3.addWidget(self.label_29)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_simufitk = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_simufitk.sizePolicy().hasHeightForWidth())
        self.lineEdit_simufitk.setSizePolicy(sizePolicy)
        self.lineEdit_simufitk.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_simufitk.setFont(font)
        self.lineEdit_simufitk.setReadOnly(True)
        self.lineEdit_simufitk.setObjectName("lineEdit_simufitk")
        self.gridLayout_3.addWidget(self.lineEdit_simufitk, 1, 1, 1, 1)
        self.lineEdit_simufittauminor = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_simufittauminor.sizePolicy().hasHeightForWidth())
        self.lineEdit_simufittauminor.setSizePolicy(sizePolicy)
        self.lineEdit_simufittauminor.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_simufittauminor.setFont(font)
        self.lineEdit_simufittauminor.setReadOnly(True)
        self.lineEdit_simufittauminor.setObjectName("lineEdit_simufittauminor")
        self.gridLayout_3.addWidget(self.lineEdit_simufittauminor, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 1, 1, 1)
        self.lineEdit_simufitEt = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_simufitEt.sizePolicy().hasHeightForWidth())
        self.lineEdit_simufitEt.setSizePolicy(sizePolicy)
        self.lineEdit_simufitEt.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_simufitEt.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_simufitEt.setFont(font)
        self.lineEdit_simufitEt.setReadOnly(True)
        self.lineEdit_simufitEt.setObjectName("lineEdit_simufitEt")
        self.gridLayout_3.addWidget(self.lineEdit_simufitEt, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.pushButton_showfitting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_showfitting.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_showfitting.sizePolicy().hasHeightForWidth())
        self.pushButton_showfitting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_showfitting.setFont(font)
        self.pushButton_showfitting.setObjectName("pushButton_showfitting")
        self.verticalLayout_3.addWidget(self.pushButton_showfitting)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_1dplot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1dplot.sizePolicy().hasHeightForWidth())
        self.pushButton_1dplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_1dplot.setFont(font)
        self.pushButton_1dplot.setObjectName("pushButton_1dplot")
        self.horizontalLayout_3.addWidget(self.pushButton_1dplot)
        self.pushButton_2dplot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2dplot.sizePolicy().hasHeightForWidth())
        self.pushButton_2dplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_2dplot.setFont(font)
        self.pushButton_2dplot.setObjectName("pushButton_2dplot")
        self.horizontalLayout_3.addWidget(self.pushButton_2dplot)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        IDLS_analyzer_dpss.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IDLS_analyzer_dpss)
        self.statusbar.setObjectName("statusbar")
        IDLS_analyzer_dpss.setStatusBar(self.statusbar)

        self.retranslateUi(IDLS_analyzer_dpss)
        QtCore.QMetaObject.connectSlotsByName(IDLS_analyzer_dpss)

    def retranslateUi(self, IDLS_analyzer_dpss):
        _translate = QtCore.QCoreApplication.translate
        IDLS_analyzer_dpss.setWindowTitle(_translate("IDLS_analyzer_dpss", "Data analysis"))
        self.pushButton_back.setText(_translate("IDLS_analyzer_dpss", "Back to \n"
" Selecting \n"
" Data"))
        self.label_9.setText(_translate("IDLS_analyzer_dpss", "Data to analysis"))
        self.pushButton_set2.setText(_translate("IDLS_analyzer_dpss", "Set"))
        self.comboBox_plotopt2.setItemText(0, _translate("IDLS_analyzer_dpss", "Linear plot"))
        self.comboBox_plotopt2.setItemText(1, _translate("IDLS_analyzer_dpss", "Standard"))
        self.comboBox_plotopt2.setItemText(2, _translate("IDLS_analyzer_dpss", "Inverse Lifetime"))
        self.label_5.setText(_translate("IDLS_analyzer_dpss", "and last"))
        self.lineEdit_fitini2.setText(_translate("IDLS_analyzer_dpss", "5"))
        self.label_3.setText(_translate("IDLS_analyzer_dpss", "%"))
        self.label.setText(_translate("IDLS_analyzer_dpss", "Fitting initial value from:"))
        self.pushButton_dpss.setText(_translate("IDLS_analyzer_dpss", "DPSS / Newton method"))
        self.label_10.setText(_translate("IDLS_analyzer_dpss", "Fiited result list"))
        self.pushButton_delfitres.setText(_translate("IDLS_analyzer_dpss", "Delete"))
        self.radioButton_ind.setText(_translate("IDLS_analyzer_dpss", "Fitting independently"))
        self.label_4.setText(_translate("IDLS_analyzer_dpss", "first"))
        self.lineEdit_fitini1.setText(_translate("IDLS_analyzer_dpss", "5"))
        self.label_2.setText(_translate("IDLS_analyzer_dpss", "%"))
        self.pushButton_onefit.setText(_translate("IDLS_analyzer_dpss", "One defect fit"))
        self.pushButton_twofit.setText(_translate("IDLS_analyzer_dpss", "Two defects fit"))
        self.pushButton_twolevelsfit.setText(_translate("IDLS_analyzer_dpss", "One defect \n"
" two levels fit"))
        self.pushButton_acceptfit.setText(_translate("IDLS_analyzer_dpss", "Accept to fitting result"))
        self.radioButton_simu.setText(_translate("IDLS_analyzer_dpss", "Simultaneously fitting "))
        self.label_16.setText(_translate("IDLS_analyzer_dpss", "Et lower bound"))
        self.lineEdit_Etlb.setText(_translate("IDLS_analyzer_dpss", "-0.5"))
        self.lineEdit_klb.setText(_translate("IDLS_analyzer_dpss", "0.01"))
        self.label_11.setText(_translate("IDLS_analyzer_dpss", "No. of Et step"))
        self.label_12.setText(_translate("IDLS_analyzer_dpss", "No. of k step"))
        self.label_13.setText(_translate("IDLS_analyzer_dpss", "Et upper bound"))
        self.label_15.setText(_translate("IDLS_analyzer_dpss", "k lower bound"))
        self.lineEdit_dk.setText(_translate("IDLS_analyzer_dpss", "10"))
        self.lineEdit_kup.setText(_translate("IDLS_analyzer_dpss", "100"))
        self.lineEdit_dEt.setText(_translate("IDLS_analyzer_dpss", "10"))
        self.lineEdit_Etub.setText(_translate("IDLS_analyzer_dpss", "0.5"))
        self.label_14.setText(_translate("IDLS_analyzer_dpss", "k upper bound"))
        self.checkBox_sametaum.setText(_translate("IDLS_analyzer_dpss", "Keep the same Tau_minor for all data "))
        self.pushButton_simufit.setText(_translate("IDLS_analyzer_dpss", "Fit !"))
        self.label_29.setText(_translate("IDLS_analyzer_dpss", "Fitting result"))
        self.label_20.setText(_translate("IDLS_analyzer_dpss", "Tau_minor (300K)"))
        self.label_21.setText(_translate("IDLS_analyzer_dpss", "Et"))
        self.label_27.setText(_translate("IDLS_analyzer_dpss", "k"))
        self.pushButton_showfitting.setText(_translate("IDLS_analyzer_dpss", "Plot the best fitting curves"))
        self.pushButton_1dplot.setText(_translate("IDLS_analyzer_dpss", "1D plot"))
        self.pushButton_2dplot.setText(_translate("IDLS_analyzer_dpss", "2D plot"))

