# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSanalysis.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IDLS_analyzer_dpss(object):
    def setupUi(self, IDLS_analyzer_dpss):
        IDLS_analyzer_dpss.setObjectName("IDLS_analyzer_dpss")
        IDLS_analyzer_dpss.resize(1525, 893)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IDLS_analyzer_dpss.sizePolicy().hasHeightForWidth())
        IDLS_analyzer_dpss.setSizePolicy(sizePolicy)
        IDLS_analyzer_dpss.setMinimumSize(QtCore.QSize(0, 0))
        IDLS_analyzer_dpss.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(IDLS_analyzer_dpss)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_back.sizePolicy().hasHeightForWidth())
        self.pushButton_back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_4.addWidget(self.pushButton_back)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.listWidget_fit = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_fit.sizePolicy().hasHeightForWidth())
        self.listWidget_fit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.listWidget_fit.setFont(font)
        self.listWidget_fit.setObjectName("listWidget_fit")
        self.verticalLayout_2.addWidget(self.listWidget_fit)
        self.pushButton_set2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set2.sizePolicy().hasHeightForWidth())
        self.pushButton_set2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_set2.setFont(font)
        self.pushButton_set2.setObjectName("pushButton_set2")
        self.verticalLayout_2.addWidget(self.pushButton_set2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_expplot2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_expplot2.setFont(font)
        self.pushButton_expplot2.setObjectName("pushButton_expplot2")
        self.horizontalLayout_7.addWidget(self.pushButton_expplot2)
        self.comboBox_plotopt2 = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_plotopt2.sizePolicy().hasHeightForWidth())
        self.comboBox_plotopt2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.comboBox_plotopt2.setFont(font)
        self.comboBox_plotopt2.setObjectName("comboBox_plotopt2")
        self.comboBox_plotopt2.addItem("")
        self.comboBox_plotopt2.addItem("")
        self.comboBox_plotopt2.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_plotopt2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_onefit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_onefit.sizePolicy().hasHeightForWidth())
        self.pushButton_onefit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_onefit.setFont(font)
        self.pushButton_onefit.setObjectName("pushButton_onefit")
        self.verticalLayout_7.addWidget(self.pushButton_onefit)
        self.pushButton_twofit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_twofit.sizePolicy().hasHeightForWidth())
        self.pushButton_twofit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_twofit.setFont(font)
        self.pushButton_twofit.setObjectName("pushButton_twofit")
        self.verticalLayout_7.addWidget(self.pushButton_twofit)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_fitini2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fitini2.sizePolicy().hasHeightForWidth())
        self.lineEdit_fitini2.setSizePolicy(sizePolicy)
        self.lineEdit_fitini2.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_fitini2.setFont(font)
        self.lineEdit_fitini2.setObjectName("lineEdit_fitini2")
        self.horizontalLayout_6.addWidget(self.lineEdit_fitini2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.pushButton_dpss = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dpss.sizePolicy().hasHeightForWidth())
        self.pushButton_dpss.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_dpss.setFont(font)
        self.pushButton_dpss.setObjectName("pushButton_dpss")
        self.gridLayout_2.addWidget(self.pushButton_dpss, 3, 1, 1, 1)
        self.listWidget_fitres = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_fitres.sizePolicy().hasHeightForWidth())
        self.listWidget_fitres.setSizePolicy(sizePolicy)
        self.listWidget_fitres.setMinimumSize(QtCore.QSize(100, 0))
        self.listWidget_fitres.setObjectName("listWidget_fitres")
        self.gridLayout_2.addWidget(self.listWidget_fitres, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        self.pushButton_delfitres = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delfitres.sizePolicy().hasHeightForWidth())
        self.pushButton_delfitres.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_delfitres.setFont(font)
        self.pushButton_delfitres.setObjectName("pushButton_delfitres")
        self.gridLayout_2.addWidget(self.pushButton_delfitres, 2, 1, 1, 1)
        self.radioButton_ind = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ind.sizePolicy().hasHeightForWidth())
        self.radioButton_ind.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.radioButton_ind.setFont(font)
        self.radioButton_ind.setChecked(True)
        self.radioButton_ind.setObjectName("radioButton_ind")
        self.gridLayout_2.addWidget(self.radioButton_ind, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_fitini1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fitini1.sizePolicy().hasHeightForWidth())
        self.lineEdit_fitini1.setSizePolicy(sizePolicy)
        self.lineEdit_fitini1.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_fitini1.setFont(font)
        self.lineEdit_fitini1.setObjectName("lineEdit_fitini1")
        self.horizontalLayout.addWidget(self.lineEdit_fitini1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.pushButton_acceptfit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_acceptfit.sizePolicy().hasHeightForWidth())
        self.pushButton_acceptfit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_acceptfit.setFont(font)
        self.pushButton_acceptfit.setObjectName("pushButton_acceptfit")
        self.verticalLayout_3.addWidget(self.pushButton_acceptfit)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.radioButton_simu = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_simu.sizePolicy().hasHeightForWidth())
        self.radioButton_simu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.radioButton_simu.setFont(font)
        self.radioButton_simu.setObjectName("radioButton_simu")
        self.verticalLayout_3.addWidget(self.radioButton_simu)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_Etlb = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Etlb.sizePolicy().hasHeightForWidth())
        self.lineEdit_Etlb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_Etlb.setFont(font)
        self.lineEdit_Etlb.setObjectName("lineEdit_Etlb")
        self.gridLayout.addWidget(self.lineEdit_Etlb, 3, 0, 1, 1)
        self.lineEdit_klb = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_klb.sizePolicy().hasHeightForWidth())
        self.lineEdit_klb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_klb.setFont(font)
        self.lineEdit_klb.setObjectName("lineEdit_klb")
        self.gridLayout.addWidget(self.lineEdit_klb, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.lineEdit_dk = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dk.sizePolicy().hasHeightForWidth())
        self.lineEdit_dk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_dk.setFont(font)
        self.lineEdit_dk.setObjectName("lineEdit_dk")
        self.gridLayout.addWidget(self.lineEdit_dk, 6, 2, 1, 1)
        self.lineEdit_kup = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_kup.sizePolicy().hasHeightForWidth())
        self.lineEdit_kup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_kup.setFont(font)
        self.lineEdit_kup.setObjectName("lineEdit_kup")
        self.gridLayout.addWidget(self.lineEdit_kup, 6, 1, 1, 1)
        self.lineEdit_dEt = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dEt.sizePolicy().hasHeightForWidth())
        self.lineEdit_dEt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_dEt.setFont(font)
        self.lineEdit_dEt.setObjectName("lineEdit_dEt")
        self.gridLayout.addWidget(self.lineEdit_dEt, 3, 2, 1, 1)
        self.lineEdit_Etub = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Etub.sizePolicy().hasHeightForWidth())
        self.lineEdit_Etub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_Etub.setFont(font)
        self.lineEdit_Etub.setObjectName("lineEdit_Etub")
        self.gridLayout.addWidget(self.lineEdit_Etub, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_sametaum = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_sametaum.sizePolicy().hasHeightForWidth())
        self.checkBox_sametaum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.checkBox_sametaum.setFont(font)
        self.checkBox_sametaum.setChecked(True)
        self.checkBox_sametaum.setObjectName("checkBox_sametaum")
        self.horizontalLayout_8.addWidget(self.checkBox_sametaum)
        self.pushButton_simufit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_simufit.sizePolicy().hasHeightForWidth())
        self.pushButton_simufit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_simufit.setFont(font)
        self.pushButton_simufit.setObjectName("pushButton_simufit")
        self.horizontalLayout_8.addWidget(self.pushButton_simufit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_9.addWidget(self.label_29)
        self.listWidget_simufitlist = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_simufitlist.sizePolicy().hasHeightForWidth())
        self.listWidget_simufitlist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_simufitlist.setFont(font)
        self.listWidget_simufitlist.setObjectName("listWidget_simufitlist")
        self.horizontalLayout_9.addWidget(self.listWidget_simufitlist)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_simufitk = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_simufitk.sizePolicy().hasHeightForWidth())
        self.lineEdit_simufitk.setSizePolicy(sizePolicy)
        self.lineEdit_simufitk.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_simufitk.setFont(font)
        self.lineEdit_simufitk.setReadOnly(True)
        self.lineEdit_simufitk.setObjectName("lineEdit_simufitk")
        self.gridLayout_3.addWidget(self.lineEdit_simufitk, 1, 1, 1, 1)
        self.lineEdit_simufittauminor = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_simufittauminor.sizePolicy().hasHeightForWidth())
        self.lineEdit_simufittauminor.setSizePolicy(sizePolicy)
        self.lineEdit_simufittauminor.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_simufittauminor.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_simufittauminor.setFont(font)
        self.lineEdit_simufittauminor.setReadOnly(True)
        self.lineEdit_simufittauminor.setObjectName("lineEdit_simufittauminor")
        self.gridLayout_3.addWidget(self.lineEdit_simufittauminor, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 1, 1, 1)
        self.lineEdit_simufitEt = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_simufitEt.sizePolicy().hasHeightForWidth())
        self.lineEdit_simufitEt.setSizePolicy(sizePolicy)
        self.lineEdit_simufitEt.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_simufitEt.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.lineEdit_simufitEt.setFont(font)
        self.lineEdit_simufitEt.setReadOnly(True)
        self.lineEdit_simufitEt.setObjectName("lineEdit_simufitEt")
        self.gridLayout_3.addWidget(self.lineEdit_simufitEt, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.pushButton_showfitting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_showfitting.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_showfitting.sizePolicy().hasHeightForWidth())
        self.pushButton_showfitting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_showfitting.setFont(font)
        self.pushButton_showfitting.setObjectName("pushButton_showfitting")
        self.verticalLayout_3.addWidget(self.pushButton_showfitting)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_1dplot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1dplot.sizePolicy().hasHeightForWidth())
        self.pushButton_1dplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_1dplot.setFont(font)
        self.pushButton_1dplot.setObjectName("pushButton_1dplot")
        self.horizontalLayout_3.addWidget(self.pushButton_1dplot)
        self.pushButton_2dplot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2dplot.sizePolicy().hasHeightForWidth())
        self.pushButton_2dplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_2dplot.setFont(font)
        self.pushButton_2dplot.setObjectName("pushButton_2dplot")
        self.horizontalLayout_3.addWidget(self.pushButton_2dplot)
        self.pushButton_exportsimu = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exportsimu.sizePolicy().hasHeightForWidth())
        self.pushButton_exportsimu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_exportsimu.setFont(font)
        self.pushButton_exportsimu.setObjectName("pushButton_exportsimu")
        self.horizontalLayout_3.addWidget(self.pushButton_exportsimu)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_advfit = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_advfit.sizePolicy().hasHeightForWidth())
        self.radioButton_advfit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_advfit.setFont(font)
        self.radioButton_advfit.setObjectName("radioButton_advfit")
        self.verticalLayout_6.addWidget(self.radioButton_advfit)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_j0 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_j0.sizePolicy().hasHeightForWidth())
        self.checkBox_j0.setSizePolicy(sizePolicy)
        self.checkBox_j0.setText("")
        self.checkBox_j0.setObjectName("checkBox_j0")
        self.gridLayout_4.addWidget(self.checkBox_j0, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 0, 0, 1, 1)
        self.lineEdit_d2Et = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d2Et.sizePolicy().hasHeightForWidth())
        self.lineEdit_d2Et.setSizePolicy(sizePolicy)
        self.lineEdit_d2Et.setObjectName("lineEdit_d2Et")
        self.gridLayout_6.addWidget(self.lineEdit_d2Et, 0, 1, 1, 1)
        self.lineEdit_d2k = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d2k.sizePolicy().hasHeightForWidth())
        self.lineEdit_d2k.setSizePolicy(sizePolicy)
        self.lineEdit_d2k.setObjectName("lineEdit_d2k")
        self.gridLayout_6.addWidget(self.lineEdit_d2k, 1, 1, 1, 1)
        self.lineEdit_d2tau = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d2tau.sizePolicy().hasHeightForWidth())
        self.lineEdit_d2tau.setSizePolicy(sizePolicy)
        self.lineEdit_d2tau.setObjectName("lineEdit_d2tau")
        self.gridLayout_6.addWidget(self.lineEdit_d2tau, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 3, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_fixd2Et = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd2Et.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd2Et.setSizePolicy(sizePolicy)
        self.checkBox_fixd2Et.setText("")
        self.checkBox_fixd2Et.setObjectName("checkBox_fixd2Et")
        self.verticalLayout_10.addWidget(self.checkBox_fixd2Et)
        self.checkBox_fixd2k = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd2k.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd2k.setSizePolicy(sizePolicy)
        self.checkBox_fixd2k.setText("")
        self.checkBox_fixd2k.setObjectName("checkBox_fixd2k")
        self.verticalLayout_10.addWidget(self.checkBox_fixd2k)
        self.checkBox_fixd2tau = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd2tau.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd2tau.setSizePolicy(sizePolicy)
        self.checkBox_fixd2tau.setText("")
        self.checkBox_fixd2tau.setObjectName("checkBox_fixd2tau")
        self.verticalLayout_10.addWidget(self.checkBox_fixd2tau)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 3, 3, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_fixd1Et1 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd1Et1.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd1Et1.setSizePolicy(sizePolicy)
        self.checkBox_fixd1Et1.setText("")
        self.checkBox_fixd1Et1.setObjectName("checkBox_fixd1Et1")
        self.verticalLayout_9.addWidget(self.checkBox_fixd1Et1)
        self.checkBox_fixd1k = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd1k.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd1k.setSizePolicy(sizePolicy)
        self.checkBox_fixd1k.setText("")
        self.checkBox_fixd1k.setObjectName("checkBox_fixd1k")
        self.verticalLayout_9.addWidget(self.checkBox_fixd1k)
        self.checkBox_fixd1tau = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd1tau.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd1tau.setSizePolicy(sizePolicy)
        self.checkBox_fixd1tau.setText("")
        self.checkBox_fixd1tau.setObjectName("checkBox_fixd1tau")
        self.verticalLayout_9.addWidget(self.checkBox_fixd1tau)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 2, 3, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 1)
        self.lineEdit_d1Et = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d1Et.sizePolicy().hasHeightForWidth())
        self.lineEdit_d1Et.setSizePolicy(sizePolicy)
        self.lineEdit_d1Et.setObjectName("lineEdit_d1Et")
        self.gridLayout_5.addWidget(self.lineEdit_d1Et, 0, 1, 1, 1)
        self.lineEdit_d1k = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d1k.sizePolicy().hasHeightForWidth())
        self.lineEdit_d1k.setSizePolicy(sizePolicy)
        self.lineEdit_d1k.setObjectName("lineEdit_d1k")
        self.gridLayout_5.addWidget(self.lineEdit_d1k, 1, 1, 1, 1)
        self.lineEdit_d1tau = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d1tau.sizePolicy().hasHeightForWidth())
        self.lineEdit_d1tau.setSizePolicy(sizePolicy)
        self.lineEdit_d1tau.setObjectName("lineEdit_d1tau")
        self.gridLayout_5.addWidget(self.lineEdit_d1tau, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 2, 2, 1, 1)
        self.checkBox_fixj0 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixj0.sizePolicy().hasHeightForWidth())
        self.checkBox_fixj0.setSizePolicy(sizePolicy)
        self.checkBox_fixj0.setText("")
        self.checkBox_fixj0.setObjectName("checkBox_fixj0")
        self.gridLayout_4.addWidget(self.checkBox_fixj0, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 3, 1, 1, 1)
        self.checkBox_def1 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_def1.sizePolicy().hasHeightForWidth())
        self.checkBox_def1.setSizePolicy(sizePolicy)
        self.checkBox_def1.setText("")
        self.checkBox_def1.setObjectName("checkBox_def1")
        self.gridLayout_4.addWidget(self.checkBox_def1, 2, 0, 1, 1)
        self.lineEdit_j0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_j0.sizePolicy().hasHeightForWidth())
        self.lineEdit_j0.setSizePolicy(sizePolicy)
        self.lineEdit_j0.setObjectName("lineEdit_j0")
        self.gridLayout_4.addWidget(self.lineEdit_j0, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.checkBox_def2 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_def2.sizePolicy().hasHeightForWidth())
        self.checkBox_def2.setSizePolicy(sizePolicy)
        self.checkBox_def2.setText("")
        self.checkBox_def2.setObjectName("checkBox_def2")
        self.gridLayout_4.addWidget(self.checkBox_def2, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 2, 1, 1)
        self.checkBox_def3 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_def3.sizePolicy().hasHeightForWidth())
        self.checkBox_def3.setSizePolicy(sizePolicy)
        self.checkBox_def3.setText("")
        self.checkBox_def3.setObjectName("checkBox_def3")
        self.gridLayout_4.addWidget(self.checkBox_def3, 4, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 4, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 4, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 5, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 0, 0, 1, 1)
        self.lineEdit_d3Et1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d3Et1.sizePolicy().hasHeightForWidth())
        self.lineEdit_d3Et1.setSizePolicy(sizePolicy)
        self.lineEdit_d3Et1.setObjectName("lineEdit_d3Et1")
        self.gridLayout_7.addWidget(self.lineEdit_d3Et1, 0, 1, 1, 1)
        self.lineEdit_d3Et2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d3Et2.sizePolicy().hasHeightForWidth())
        self.lineEdit_d3Et2.setSizePolicy(sizePolicy)
        self.lineEdit_d3Et2.setObjectName("lineEdit_d3Et2")
        self.gridLayout_7.addWidget(self.lineEdit_d3Et2, 1, 1, 1, 1)
        self.lineEdit_d3k1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d3k1.sizePolicy().hasHeightForWidth())
        self.lineEdit_d3k1.setSizePolicy(sizePolicy)
        self.lineEdit_d3k1.setObjectName("lineEdit_d3k1")
        self.gridLayout_7.addWidget(self.lineEdit_d3k1, 2, 1, 1, 1)
        self.lineEdit_d3k2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d3k2.sizePolicy().hasHeightForWidth())
        self.lineEdit_d3k2.setSizePolicy(sizePolicy)
        self.lineEdit_d3k2.setObjectName("lineEdit_d3k2")
        self.gridLayout_7.addWidget(self.lineEdit_d3k2, 3, 1, 1, 1)
        self.lineEdit_d3tau1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d3tau1.sizePolicy().hasHeightForWidth())
        self.lineEdit_d3tau1.setSizePolicy(sizePolicy)
        self.lineEdit_d3tau1.setObjectName("lineEdit_d3tau1")
        self.gridLayout_7.addWidget(self.lineEdit_d3tau1, 4, 1, 1, 1)
        self.lineEdit_d3tau2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_d3tau2.sizePolicy().hasHeightForWidth())
        self.lineEdit_d3tau2.setSizePolicy(sizePolicy)
        self.lineEdit_d3tau2.setObjectName("lineEdit_d3tau2")
        self.gridLayout_7.addWidget(self.lineEdit_d3tau2, 5, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 4, 2, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_fixd3Et1 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd3Et1.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd3Et1.setSizePolicy(sizePolicy)
        self.checkBox_fixd3Et1.setText("")
        self.checkBox_fixd3Et1.setObjectName("checkBox_fixd3Et1")
        self.verticalLayout_11.addWidget(self.checkBox_fixd3Et1)
        self.checkBox_fixd3Et2 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd3Et2.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd3Et2.setSizePolicy(sizePolicy)
        self.checkBox_fixd3Et2.setText("")
        self.checkBox_fixd3Et2.setObjectName("checkBox_fixd3Et2")
        self.verticalLayout_11.addWidget(self.checkBox_fixd3Et2)
        self.checkBox_fixd3k1 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd3k1.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd3k1.setSizePolicy(sizePolicy)
        self.checkBox_fixd3k1.setText("")
        self.checkBox_fixd3k1.setObjectName("checkBox_fixd3k1")
        self.verticalLayout_11.addWidget(self.checkBox_fixd3k1)
        self.checkBox_fixd3k2 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd3k2.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd3k2.setSizePolicy(sizePolicy)
        self.checkBox_fixd3k2.setText("")
        self.checkBox_fixd3k2.setObjectName("checkBox_fixd3k2")
        self.verticalLayout_11.addWidget(self.checkBox_fixd3k2)
        self.checkBox_fixd3tau1 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd3tau1.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd3tau1.setSizePolicy(sizePolicy)
        self.checkBox_fixd3tau1.setText("")
        self.checkBox_fixd3tau1.setObjectName("checkBox_fixd3tau1")
        self.verticalLayout_11.addWidget(self.checkBox_fixd3tau1)
        self.checkBox_fixd3tau2 = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_fixd3tau2.sizePolicy().hasHeightForWidth())
        self.checkBox_fixd3tau2.setSizePolicy(sizePolicy)
        self.checkBox_fixd3tau2.setText("")
        self.checkBox_fixd3tau2.setObjectName("checkBox_fixd3tau2")
        self.verticalLayout_11.addWidget(self.checkBox_fixd3tau2)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 4, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(390, 0))
        self.label_38.setMaximumSize(QtCore.QSize(390, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_6.addWidget(self.label_38)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.pushButton_plotadvfit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plotadvfit.setFont(font)
        self.pushButton_plotadvfit.setObjectName("pushButton_plotadvfit")
        self.verticalLayout_6.addWidget(self.pushButton_plotadvfit)
        self.pushButton_advfit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_advfit.sizePolicy().hasHeightForWidth())
        self.pushButton_advfit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_advfit.setFont(font)
        self.pushButton_advfit.setObjectName("pushButton_advfit")
        self.verticalLayout_6.addWidget(self.pushButton_advfit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_expadvfit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_expadvfit.sizePolicy().hasHeightForWidth())
        self.pushButton_expadvfit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_expadvfit.setFont(font)
        self.pushButton_expadvfit.setObjectName("pushButton_expadvfit")
        self.horizontalLayout_2.addWidget(self.pushButton_expadvfit)
        self.pushButton_loadadvfit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_loadadvfit.setFont(font)
        self.pushButton_loadadvfit.setObjectName("pushButton_loadadvfit")
        self.horizontalLayout_2.addWidget(self.pushButton_loadadvfit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        IDLS_analyzer_dpss.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IDLS_analyzer_dpss)
        self.statusbar.setObjectName("statusbar")
        IDLS_analyzer_dpss.setStatusBar(self.statusbar)

        self.retranslateUi(IDLS_analyzer_dpss)
        QtCore.QMetaObject.connectSlotsByName(IDLS_analyzer_dpss)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_back, self.listWidget_fit)
        IDLS_analyzer_dpss.setTabOrder(self.listWidget_fit, self.pushButton_set2)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_set2, self.radioButton_ind)
        IDLS_analyzer_dpss.setTabOrder(self.radioButton_ind, self.pushButton_onefit)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_onefit, self.pushButton_twofit)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_twofit, self.lineEdit_fitini1)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_fitini1, self.lineEdit_fitini2)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_fitini2, self.pushButton_acceptfit)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_acceptfit, self.listWidget_fitres)
        IDLS_analyzer_dpss.setTabOrder(self.listWidget_fitres, self.pushButton_delfitres)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_delfitres, self.pushButton_dpss)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_dpss, self.radioButton_simu)
        IDLS_analyzer_dpss.setTabOrder(self.radioButton_simu, self.lineEdit_Etlb)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_Etlb, self.lineEdit_Etub)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_Etub, self.lineEdit_dEt)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_dEt, self.lineEdit_klb)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_klb, self.lineEdit_kup)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_kup, self.lineEdit_dk)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_dk, self.checkBox_sametaum)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_sametaum, self.pushButton_simufit)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_simufit, self.lineEdit_simufitEt)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_simufitEt, self.lineEdit_simufitk)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_simufitk, self.lineEdit_simufittauminor)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_simufittauminor, self.pushButton_showfitting)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_showfitting, self.pushButton_1dplot)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_1dplot, self.pushButton_2dplot)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_2dplot, self.pushButton_exportsimu)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_exportsimu, self.pushButton_expplot2)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_expplot2, self.comboBox_plotopt2)
        IDLS_analyzer_dpss.setTabOrder(self.comboBox_plotopt2, self.radioButton_advfit)
        IDLS_analyzer_dpss.setTabOrder(self.radioButton_advfit, self.checkBox_j0)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_j0, self.lineEdit_j0)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_j0, self.checkBox_fixj0)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixj0, self.checkBox_def1)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_def1, self.lineEdit_d1Et)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d1Et, self.checkBox_fixd1Et1)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd1Et1, self.lineEdit_d1k)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d1k, self.checkBox_fixd1k)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd1k, self.lineEdit_d1tau)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d1tau, self.checkBox_fixd1tau)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd1tau, self.checkBox_def2)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_def2, self.lineEdit_d2Et)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d2Et, self.checkBox_fixd2Et)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd2Et, self.lineEdit_d2k)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d2k, self.checkBox_fixd2k)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd2k, self.lineEdit_d2tau)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d2tau, self.checkBox_fixd2tau)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd2tau, self.checkBox_def3)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_def3, self.lineEdit_d3Et1)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d3Et1, self.checkBox_fixd3Et1)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd3Et1, self.lineEdit_d3Et2)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d3Et2, self.checkBox_fixd3Et2)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd3Et2, self.lineEdit_d3k1)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d3k1, self.checkBox_fixd3k1)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd3k1, self.lineEdit_d3k2)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d3k2, self.checkBox_fixd3k2)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd3k2, self.lineEdit_d3tau1)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d3tau1, self.checkBox_fixd3tau1)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd3tau1, self.lineEdit_d3tau2)
        IDLS_analyzer_dpss.setTabOrder(self.lineEdit_d3tau2, self.checkBox_fixd3tau2)
        IDLS_analyzer_dpss.setTabOrder(self.checkBox_fixd3tau2, self.pushButton_plotadvfit)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_plotadvfit, self.pushButton_advfit)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_advfit, self.pushButton_expadvfit)
        IDLS_analyzer_dpss.setTabOrder(self.pushButton_expadvfit, self.pushButton_loadadvfit)

    def retranslateUi(self, IDLS_analyzer_dpss):
        _translate = QtCore.QCoreApplication.translate
        IDLS_analyzer_dpss.setWindowTitle(_translate("IDLS_analyzer_dpss", "Data analysis"))
        self.pushButton_back.setText(_translate("IDLS_analyzer_dpss", "Back to \n"
" Selecting \n"
" Data"))
        self.label_9.setText(_translate("IDLS_analyzer_dpss", "Data to analysis"))
        self.pushButton_set2.setText(_translate("IDLS_analyzer_dpss", "Set"))
        self.pushButton_expplot2.setText(_translate("IDLS_analyzer_dpss", "Export plot data"))
        self.comboBox_plotopt2.setItemText(0, _translate("IDLS_analyzer_dpss", "Linear plot"))
        self.comboBox_plotopt2.setItemText(1, _translate("IDLS_analyzer_dpss", "Standard"))
        self.comboBox_plotopt2.setItemText(2, _translate("IDLS_analyzer_dpss", "Inverse Lifetime"))
        self.pushButton_onefit.setText(_translate("IDLS_analyzer_dpss", "One defect fit"))
        self.pushButton_twofit.setText(_translate("IDLS_analyzer_dpss", "Two defects fit"))
        self.label_5.setText(_translate("IDLS_analyzer_dpss", "and last"))
        self.lineEdit_fitini2.setText(_translate("IDLS_analyzer_dpss", "5"))
        self.label_3.setText(_translate("IDLS_analyzer_dpss", "%"))
        self.label.setText(_translate("IDLS_analyzer_dpss", "Fitting initial value from:"))
        self.pushButton_dpss.setText(_translate("IDLS_analyzer_dpss", "DPSS / Newton method"))
        self.label_10.setText(_translate("IDLS_analyzer_dpss", "Fitted result list"))
        self.pushButton_delfitres.setText(_translate("IDLS_analyzer_dpss", "Delete"))
        self.radioButton_ind.setText(_translate("IDLS_analyzer_dpss", "Fitting independently"))
        self.label_4.setText(_translate("IDLS_analyzer_dpss", "first"))
        self.lineEdit_fitini1.setText(_translate("IDLS_analyzer_dpss", "5"))
        self.label_2.setText(_translate("IDLS_analyzer_dpss", "%"))
        self.pushButton_acceptfit.setText(_translate("IDLS_analyzer_dpss", "Accept to fitting result"))
        self.radioButton_simu.setText(_translate("IDLS_analyzer_dpss", "Simultaneously fitting "))
        self.label_16.setText(_translate("IDLS_analyzer_dpss", "Et lower bound"))
        self.lineEdit_Etlb.setText(_translate("IDLS_analyzer_dpss", "-0.5"))
        self.lineEdit_klb.setText(_translate("IDLS_analyzer_dpss", "0.01"))
        self.label_11.setText(_translate("IDLS_analyzer_dpss", "No. of Et step"))
        self.label_12.setText(_translate("IDLS_analyzer_dpss", "No. of k step"))
        self.label_13.setText(_translate("IDLS_analyzer_dpss", "Et upper bound"))
        self.label_15.setText(_translate("IDLS_analyzer_dpss", "k lower bound"))
        self.lineEdit_dk.setText(_translate("IDLS_analyzer_dpss", "10"))
        self.lineEdit_kup.setText(_translate("IDLS_analyzer_dpss", "100"))
        self.lineEdit_dEt.setText(_translate("IDLS_analyzer_dpss", "10"))
        self.lineEdit_Etub.setText(_translate("IDLS_analyzer_dpss", "0.5"))
        self.label_14.setText(_translate("IDLS_analyzer_dpss", "k upper bound"))
        self.checkBox_sametaum.setText(_translate("IDLS_analyzer_dpss", "Keep the same τ_minor for all data "))
        self.pushButton_simufit.setText(_translate("IDLS_analyzer_dpss", "Fit !"))
        self.label_29.setText(_translate("IDLS_analyzer_dpss", "Fitting result for"))
        self.label_20.setText(_translate("IDLS_analyzer_dpss", "<html><head/><body><p>τ<span style=\" vertical-align:sub;\">minor</span> @ 300K (s)</p></body></html>"))
        self.label_21.setText(_translate("IDLS_analyzer_dpss", "Et"))
        self.label_27.setText(_translate("IDLS_analyzer_dpss", "k"))
        self.pushButton_showfitting.setText(_translate("IDLS_analyzer_dpss", "Plot the best fitting curves"))
        self.pushButton_1dplot.setText(_translate("IDLS_analyzer_dpss", "1D plot"))
        self.pushButton_2dplot.setText(_translate("IDLS_analyzer_dpss", "2D plot"))
        self.pushButton_exportsimu.setText(_translate("IDLS_analyzer_dpss", "Export results"))
        self.radioButton_advfit.setText(_translate("IDLS_analyzer_dpss", "Advanced Fitting"))
        self.label_17.setText(_translate("IDLS_analyzer_dpss", "Fixed"))
        self.label_18.setText(_translate("IDLS_analyzer_dpss", "J0 (A/cm2) "))
        self.label_28.setText(_translate("IDLS_analyzer_dpss", "k"))
        self.label_30.setText(_translate("IDLS_analyzer_dpss", "τ<sub>minor"))
        self.label_26.setText(_translate("IDLS_analyzer_dpss", "Et"))
        self.label_24.setText(_translate("IDLS_analyzer_dpss", "τ<sub>minor"))
        self.label_23.setText(_translate("IDLS_analyzer_dpss", "k"))
        self.label_22.setText(_translate("IDLS_analyzer_dpss", "Et"))
        self.label_19.setText(_translate("IDLS_analyzer_dpss", "1 level \n"
"defect 1"))
        self.label_7.setText(_translate("IDLS_analyzer_dpss", "Components"))
        self.label_25.setText(_translate("IDLS_analyzer_dpss", "1 level\n"
"defect 2"))
        self.label_6.setText(_translate("IDLS_analyzer_dpss", "Enable"))
        self.label_8.setText(_translate("IDLS_analyzer_dpss", "Value"))
        self.label_31.setText(_translate("IDLS_analyzer_dpss", "2 level\n"
"defect"))
        self.label_36.setText(_translate("IDLS_analyzer_dpss", "<html><head/><body><p>&tau;<span style=\" vertical-align:sub;\">n1</span></p></body></html>"))
        self.label_37.setText(_translate("IDLS_analyzer_dpss", "&tau;<sub>p2"))
        self.label_35.setText(_translate("IDLS_analyzer_dpss", "k2"))
        self.label_34.setText(_translate("IDLS_analyzer_dpss", "k1"))
        self.label_33.setText(_translate("IDLS_analyzer_dpss", "Et2"))
        self.label_32.setText(_translate("IDLS_analyzer_dpss", "Et1"))
        self.label_38.setText(_translate("IDLS_analyzer_dpss", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Sorry, currently under construction.</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Will come in the next release.</span></p><p>The advanced fitting function here is for testing only. It gives the flexibility to choose recombination components. You can also simultanesly fit multiple files, but for now the defect concentration needs to be the same. You can put initial values for the fitting.</p></body></html>"))
        self.pushButton_plotadvfit.setText(_translate("IDLS_analyzer_dpss", "Plot the fitting result with current selected sample info"))
        self.pushButton_advfit.setText(_translate("IDLS_analyzer_dpss", "Fit !"))
        self.pushButton_expadvfit.setText(_translate("IDLS_analyzer_dpss", "Export"))
        self.pushButton_loadadvfit.setText(_translate("IDLS_analyzer_dpss", "Load"))

