# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSProcess.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IDLSanalyzer(object):
    def setupUi(self, IDLSanalyzer):
        IDLSanalyzer.setObjectName("IDLSanalyzer")
        IDLSanalyzer.resize(790, 860)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IDLSanalyzer.sizePolicy().hasHeightForWidth())
        IDLSanalyzer.setSizePolicy(sizePolicy)
        IDLSanalyzer.setMinimumSize(QtCore.QSize(790, 860))
        IDLSanalyzer.setMaximumSize(QtCore.QSize(790, 860))
        self.centralwidget = QtWidgets.QWidget(IDLSanalyzer)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(11, 299, 769, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.listWidget_plotlist = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget_plotlist.setGeometry(QtCore.QRect(10, 70, 131, 181))
        self.listWidget_plotlist.setObjectName("listWidget_plotlist")
        self.pushButton_delplot = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_delplot.setGeometry(QtCore.QRect(30, 260, 75, 23))
        self.pushButton_delplot.setObjectName("pushButton_delplot")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 20, 611, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_plotwhat = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_plotwhat.setGeometry(QtCore.QRect(10, 30, 131, 22))
        self.comboBox_plotwhat.setObjectName("comboBox_plotwhat")
        self.comboBox_plotwhat.addItem("")
        self.comboBox_plotwhat.addItem("")
        self.comboBox_plotinverse = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_plotinverse.setGeometry(QtCore.QRect(20, 340, 101, 22))
        self.comboBox_plotinverse.setObjectName("comboBox_plotinverse")
        self.comboBox_plotinverse.addItem("")
        self.comboBox_plotinverse.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 280))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 280))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_load = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_load.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_set = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_set.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.pushButton_set.setObjectName("pushButton_set")
        self.pushButton_del = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_del.setGeometry(QtCore.QRect(170, 20, 75, 23))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_expdata = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_expdata.setGeometry(QtCore.QRect(10, 250, 61, 23))
        self.pushButton_expdata.setObjectName("pushButton_expdata")
        self.pushButton_data2plot = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_data2plot.setGeometry(QtCore.QRect(80, 250, 71, 23))
        self.pushButton_data2plot.setObjectName("pushButton_data2plot")
        self.pushButton_data2fit = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_data2fit.setGeometry(QtCore.QRect(160, 250, 81, 23))
        self.pushButton_data2fit.setObjectName("pushButton_data2fit")
        self.listWidget_data = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_data.setGeometry(QtCore.QRect(10, 50, 231, 191))
        self.listWidget_data.setObjectName("listWidget_data")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 10, 251, 280))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 280))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_sub2data = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_sub2data.setGeometry(QtCore.QRect(20, 180, 121, 23))
        self.pushButton_sub2data.setObjectName("pushButton_sub2data")
        self.pushButton_corp = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_corp.setGeometry(QtCore.QRect(20, 20, 111, 23))
        self.pushButton_corp.setObjectName("pushButton_corp")
        self.pushButton_intcorrect = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_intcorrect.setGeometry(QtCore.QRect(20, 140, 111, 23))
        self.pushButton_intcorrect.setObjectName("pushButton_intcorrect")
        self.lineEdit_croplow = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_croplow.setGeometry(QtCore.QRect(50, 60, 61, 20))
        self.lineEdit_croplow.setObjectName("lineEdit_croplow")
        self.lineEdit_crophigh = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_crophigh.setGeometry(QtCore.QRect(140, 60, 61, 20))
        self.lineEdit_crophigh.setObjectName("lineEdit_crophigh")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(120, 60, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(210, 60, 31, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_mergetwo = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_mergetwo.setGeometry(QtCore.QRect(20, 220, 75, 23))
        self.pushButton_mergetwo.setObjectName("pushButton_mergetwo")
        self.pushButton_corpconfirm = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_corpconfirm.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.pushButton_corpconfirm.setObjectName("pushButton_corpconfirm")
        self.pushButton_corpcancel = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_corpcancel.setGeometry(QtCore.QRect(120, 100, 75, 23))
        self.pushButton_corpcancel.setObjectName("pushButton_corpcancel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(530, 10, 251, 280))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 280))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_Analysis = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Analysis.setGeometry(QtCore.QRect(160, 60, 75, 171))
        self.pushButton_Analysis.setObjectName("pushButton_Analysis")
        self.listWidget_analysis = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_analysis.setGeometry(QtCore.QRect(10, 30, 141, 211))
        self.listWidget_analysis.setObjectName("listWidget_analysis")
        self.pushButton_delanalysis = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_delanalysis.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.pushButton_delanalysis.setObjectName("pushButton_delanalysis")
        self.pushButton_viewset = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_viewset.setGeometry(QtCore.QRect(100, 250, 75, 23))
        self.pushButton_viewset.setObjectName("pushButton_viewset")
        IDLSanalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IDLSanalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        IDLSanalyzer.setMenuBar(self.menubar)
        self.action1 = QtWidgets.QAction(IDLSanalyzer)
        self.action1.setObjectName("action1")
        self.action1_2 = QtWidgets.QAction(IDLSanalyzer)
        self.action1_2.setObjectName("action1_2")
        self.action1_3 = QtWidgets.QAction(IDLSanalyzer)
        self.action1_3.setObjectName("action1_3")

        self.retranslateUi(IDLSanalyzer)
        QtCore.QMetaObject.connectSlotsByName(IDLSanalyzer)

    def retranslateUi(self, IDLSanalyzer):
        _translate = QtCore.QCoreApplication.translate
        IDLSanalyzer.setWindowTitle(_translate("IDLSanalyzer", "IDLS analyzer"))
        self.groupBox_5.setTitle(_translate("IDLSanalyzer", "Plot Raw data"))
        self.pushButton_delplot.setText(_translate("IDLSanalyzer", "Remove"))
        self.comboBox_plotwhat.setItemText(0, _translate("IDLSanalyzer", "Plot selected"))
        self.comboBox_plotwhat.setItemText(1, _translate("IDLSanalyzer", "Plot all data to analysis"))
        self.comboBox_plotinverse.setItemText(0, _translate("IDLSanalyzer", "Lifetime"))
        self.comboBox_plotinverse.setItemText(1, _translate("IDLSanalyzer", "Inverse Lifetime"))
        self.groupBox.setTitle(_translate("IDLSanalyzer", "Raw Data input"))
        self.pushButton_load.setText(_translate("IDLSanalyzer", "Load"))
        self.pushButton_set.setText(_translate("IDLSanalyzer", "Set"))
        self.pushButton_del.setText(_translate("IDLSanalyzer", "Delete"))
        self.pushButton_expdata.setText(_translate("IDLSanalyzer", "Export"))
        self.pushButton_data2plot.setText(_translate("IDLSanalyzer", "Add to plot"))
        self.pushButton_data2fit.setText(_translate("IDLSanalyzer", "Add to analysis"))
        self.groupBox_3.setTitle(_translate("IDLSanalyzer", "Data pre-process"))
        self.pushButton_sub2data.setText(_translate("IDLSanalyzer", "Subtraction from two"))
        self.pushButton_corp.setText(_translate("IDLSanalyzer", "Crop preview"))
        self.pushButton_intcorrect.setText(_translate("IDLSanalyzer", "Intrinsic correction"))
        self.label_4.setText(_translate("IDLSanalyzer", "from"))
        self.label_5.setText(_translate("IDLSanalyzer", "to"))
        self.label_6.setText(_translate("IDLSanalyzer", "cm-3"))
        self.pushButton_mergetwo.setText(_translate("IDLSanalyzer", "Merge two"))
        self.pushButton_corpconfirm.setText(_translate("IDLSanalyzer", "Crop confirm"))
        self.pushButton_corpcancel.setText(_translate("IDLSanalyzer", "Crop cancel"))
        self.groupBox_2.setTitle(_translate("IDLSanalyzer", "Data to analysis"))
        self.pushButton_Analysis.setText(_translate("IDLSanalyzer", "Start\n"
" Analysis!"))
        self.pushButton_delanalysis.setText(_translate("IDLSanalyzer", "Remove"))
        self.pushButton_viewset.setText(_translate("IDLSanalyzer", "View setting"))
        self.action1.setText(_translate("IDLSanalyzer", "1"))
        self.action1_2.setText(_translate("IDLSanalyzer", "1"))
        self.action1_3.setText(_translate("IDLSanalyzer", "1"))

