# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSanalysis.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IDLS_analyzer_dpss(object):
    def setupUi(self, IDLS_analyzer_dpss):
        IDLS_analyzer_dpss.setObjectName("IDLS_analyzer_dpss")
        IDLS_analyzer_dpss.resize(900, 765)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IDLS_analyzer_dpss.sizePolicy().hasHeightForWidth())
        IDLS_analyzer_dpss.setSizePolicy(sizePolicy)
        IDLS_analyzer_dpss.setMinimumSize(QtCore.QSize(900, 765))
        IDLS_analyzer_dpss.setMaximumSize(QtCore.QSize(900, 765))
        self.centralwidget = QtWidgets.QWidget(IDLS_analyzer_dpss)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 10, 91, 16))
        self.label_9.setObjectName("label_9")
        self.listWidget_fitres = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_fitres.setGeometry(QtCore.QRect(750, 30, 141, 151))
        self.listWidget_fitres.setObjectName("listWidget_fitres")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 200, 601, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_ind = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ind.setGeometry(QtCore.QRect(610, 10, 131, 17))
        self.radioButton_ind.setChecked(True)
        self.radioButton_ind.setObjectName("radioButton_ind")
        self.listWidget_fit = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_fit.setGeometry(QtCore.QRect(210, 30, 201, 151))
        self.listWidget_fit.setObjectName("listWidget_fit")
        self.pushButton_onefit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_onefit.setGeometry(QtCore.QRect(620, 40, 75, 23))
        self.pushButton_onefit.setObjectName("pushButton_onefit")
        self.pushButton_twofit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_twofit.setGeometry(QtCore.QRect(620, 80, 81, 23))
        self.pushButton_twofit.setObjectName("pushButton_twofit")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(770, 10, 71, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(70, 40, 75, 141))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_set2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set2.setGeometry(QtCore.QRect(470, 60, 61, 23))
        self.pushButton_set2.setObjectName("pushButton_set2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 130, 121, 16))
        self.label.setObjectName("label")
        self.lineEdit_fitini1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fitini1.setGeometry(QtCore.QRect(670, 160, 41, 20))
        self.lineEdit_fitini1.setObjectName("lineEdit_fitini1")
        self.lineEdit_fitini2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fitini2.setGeometry(QtCore.QRect(670, 190, 41, 20))
        self.lineEdit_fitini2.setObjectName("lineEdit_fitini2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(720, 160, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(720, 190, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 160, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 190, 41, 20))
        self.label_5.setObjectName("label_5")
        self.comboBox_plotopt2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_plotopt2.setGeometry(QtCore.QRect(450, 150, 111, 22))
        self.comboBox_plotopt2.setObjectName("comboBox_plotopt2")
        self.comboBox_plotopt2.addItem("")
        self.comboBox_plotopt2.addItem("")
        self.comboBox_plotopt2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(480, 130, 51, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_acceptfit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_acceptfit.setGeometry(QtCore.QRect(620, 230, 121, 23))
        self.pushButton_acceptfit.setObjectName("pushButton_acceptfit")
        self.radioButton_simu = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_simu.setGeometry(QtCore.QRect(620, 310, 221, 41))
        self.radioButton_simu.setObjectName("radioButton_simu")
        self.pushButton_dpss = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dpss.setGeometry(QtCore.QRect(770, 220, 91, 21))
        self.pushButton_dpss.setObjectName("pushButton_dpss")
        self.pushButton_NT = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_NT.setGeometry(QtCore.QRect(770, 250, 91, 23))
        self.pushButton_NT.setObjectName("pushButton_NT")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(620, 360, 261, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_Etlb = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Etlb.setObjectName("lineEdit_Etlb")
        self.gridLayout.addWidget(self.lineEdit_Etlb, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_klb = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_klb.setObjectName("lineEdit_klb")
        self.gridLayout.addWidget(self.lineEdit_klb, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.lineEdit_Etub = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Etub.setObjectName("lineEdit_Etub")
        self.gridLayout.addWidget(self.lineEdit_Etub, 3, 1, 1, 1)
        self.lineEdit_dEt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dEt.setObjectName("lineEdit_dEt")
        self.gridLayout.addWidget(self.lineEdit_dEt, 3, 2, 1, 1)
        self.lineEdit_kup = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_kup.setObjectName("lineEdit_kup")
        self.gridLayout.addWidget(self.lineEdit_kup, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 1, 1, 1)
        self.lineEdit_dk = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dk.setObjectName("lineEdit_dk")
        self.gridLayout.addWidget(self.lineEdit_dk, 6, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(630, 590, 226, 93))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.lineEdit_simufitk = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_simufitk.setObjectName("lineEdit_simufitk")
        self.gridLayout_3.addWidget(self.lineEdit_simufitk, 1, 2, 1, 1)
        self.lineEdit_simufittauminor = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_simufittauminor.setObjectName("lineEdit_simufittauminor")
        self.gridLayout_3.addWidget(self.lineEdit_simufittauminor, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 2, 1, 1)
        self.lineEdit_simufitEt = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_simufitEt.setObjectName("lineEdit_simufitEt")
        self.gridLayout_3.addWidget(self.lineEdit_simufitEt, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 3, 0, 1, 1)
        self.lineEdit_simufitEtlb = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_simufitEtlb.setObjectName("lineEdit_simufitEtlb")
        self.gridLayout_3.addWidget(self.lineEdit_simufitEtlb, 2, 1, 1, 1)
        self.lineEdit_simufitEtub = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_simufitEtub.setObjectName("lineEdit_simufitEtub")
        self.gridLayout_3.addWidget(self.lineEdit_simufitEtub, 3, 1, 1, 1)
        self.lineEdit_simufitklb = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_simufitklb.setObjectName("lineEdit_simufitklb")
        self.gridLayout_3.addWidget(self.lineEdit_simufitklb, 2, 2, 1, 1)
        self.lineEdit_simufitkub = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_simufitkub.setObjectName("lineEdit_simufitkub")
        self.gridLayout_3.addWidget(self.lineEdit_simufitkub, 3, 2, 1, 1)
        self.pushButton_2dplot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2dplot.setGeometry(QtCore.QRect(760, 700, 91, 21))
        self.pushButton_2dplot.setObjectName("pushButton_2dplot")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(620, 570, 71, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(620, 540, 91, 16))
        self.label_30.setObjectName("label_30")
        self.lineEdit_allowrange = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_allowrange.setGeometry(QtCore.QRect(710, 540, 31, 20))
        self.lineEdit_allowrange.setObjectName("lineEdit_allowrange")
        self.pushButton_simufit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_simufit.setGeometry(QtCore.QRect(770, 530, 91, 41))
        self.pushButton_simufit.setObjectName("pushButton_simufit")
        self.pushButton_1dplot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1dplot.setGeometry(QtCore.QRect(640, 700, 91, 21))
        self.pushButton_1dplot.setObjectName("pushButton_1dplot")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(740, 540, 16, 16))
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(620, 480, 201, 31))
        self.checkBox.setObjectName("checkBox")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(700, 270, 191, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_delfitres = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delfitres.setGeometry(QtCore.QRect(790, 190, 51, 23))
        self.pushButton_delfitres.setObjectName("pushButton_delfitres")
        IDLS_analyzer_dpss.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IDLS_analyzer_dpss)
        self.statusbar.setObjectName("statusbar")
        IDLS_analyzer_dpss.setStatusBar(self.statusbar)

        self.retranslateUi(IDLS_analyzer_dpss)
        QtCore.QMetaObject.connectSlotsByName(IDLS_analyzer_dpss)

    def retranslateUi(self, IDLS_analyzer_dpss):
        _translate = QtCore.QCoreApplication.translate
        IDLS_analyzer_dpss.setWindowTitle(_translate("IDLS_analyzer_dpss", "Data analysis"))
        self.label_9.setText(_translate("IDLS_analyzer_dpss", "Data to analysis"))
        self.radioButton_ind.setText(_translate("IDLS_analyzer_dpss", "Fitting independently"))
        self.pushButton_onefit.setText(_translate("IDLS_analyzer_dpss", "One defect fit"))
        self.pushButton_twofit.setText(_translate("IDLS_analyzer_dpss", "Two defects fit"))
        self.label_10.setText(_translate("IDLS_analyzer_dpss", "Fiited result list"))
        self.pushButton_back.setText(_translate("IDLS_analyzer_dpss", "Back to \n"
" Selecting \n"
" Data"))
        self.pushButton_set2.setText(_translate("IDLS_analyzer_dpss", "Set"))
        self.label.setText(_translate("IDLS_analyzer_dpss", "Fitting initial value from:"))
        self.lineEdit_fitini1.setText(_translate("IDLS_analyzer_dpss", "5"))
        self.lineEdit_fitini2.setText(_translate("IDLS_analyzer_dpss", "5"))
        self.label_2.setText(_translate("IDLS_analyzer_dpss", "%"))
        self.label_3.setText(_translate("IDLS_analyzer_dpss", "%"))
        self.label_4.setText(_translate("IDLS_analyzer_dpss", "first"))
        self.label_5.setText(_translate("IDLS_analyzer_dpss", "and last"))
        self.comboBox_plotopt2.setItemText(0, _translate("IDLS_analyzer_dpss", "Linear plot"))
        self.comboBox_plotopt2.setItemText(1, _translate("IDLS_analyzer_dpss", "Standard"))
        self.comboBox_plotopt2.setItemText(2, _translate("IDLS_analyzer_dpss", "Inverse Lifetime"))
        self.label_6.setText(_translate("IDLS_analyzer_dpss", "Plot option"))
        self.pushButton_acceptfit.setText(_translate("IDLS_analyzer_dpss", "Accept to fitting result"))
        self.radioButton_simu.setText(_translate("IDLS_analyzer_dpss", "Simultaneously fitting \n"
"(can only do one defect fit at this stage) \n"
"(will only fit the selected items)"))
        self.pushButton_dpss.setText(_translate("IDLS_analyzer_dpss", "DPSS"))
        self.pushButton_NT.setText(_translate("IDLS_analyzer_dpss", "Newton method"))
        self.label_16.setText(_translate("IDLS_analyzer_dpss", "Et lower bound"))
        self.label_11.setText(_translate("IDLS_analyzer_dpss", "Et step"))
        self.label_14.setText(_translate("IDLS_analyzer_dpss", "k upper bound"))
        self.label_12.setText(_translate("IDLS_analyzer_dpss", "k step"))
        self.label_15.setText(_translate("IDLS_analyzer_dpss", "k lower bound"))
        self.label_13.setText(_translate("IDLS_analyzer_dpss", "Et upper bound"))
        self.label_25.setText(_translate("IDLS_analyzer_dpss", "Lower limit"))
        self.label_26.setText(_translate("IDLS_analyzer_dpss", "Best fitted"))
        self.label_20.setText(_translate("IDLS_analyzer_dpss", "Tau_minor"))
        self.label_21.setText(_translate("IDLS_analyzer_dpss", "Et"))
        self.label_27.setText(_translate("IDLS_analyzer_dpss", "k"))
        self.label_28.setText(_translate("IDLS_analyzer_dpss", "Upper limit"))
        self.pushButton_2dplot.setText(_translate("IDLS_analyzer_dpss", "2D plot"))
        self.label_29.setText(_translate("IDLS_analyzer_dpss", "Fitting result"))
        self.label_30.setText(_translate("IDLS_analyzer_dpss", "Allowance range"))
        self.lineEdit_allowrange.setText(_translate("IDLS_analyzer_dpss", "11"))
        self.pushButton_simufit.setText(_translate("IDLS_analyzer_dpss", "Fit !"))
        self.pushButton_1dplot.setText(_translate("IDLS_analyzer_dpss", "1D plot"))
        self.label_7.setText(_translate("IDLS_analyzer_dpss", "%"))
        self.checkBox.setText(_translate("IDLS_analyzer_dpss", "Keep the same Tau_minor for all data \n"
"(defect density is the same)"))
        self.label_8.setText(_translate("IDLS_analyzer_dpss", "(will only calculate the selected items)"))
        self.pushButton_delfitres.setText(_translate("IDLS_analyzer_dpss", "Delete"))

