# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSProcess.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IDLSanalyzer(object):
    def setupUi(self, IDLSanalyzer):
        IDLSanalyzer.setObjectName("IDLSanalyzer")
        IDLSanalyzer.resize(803, 898)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IDLSanalyzer.sizePolicy().hasHeightForWidth())
        IDLSanalyzer.setSizePolicy(sizePolicy)
        IDLSanalyzer.setMinimumSize(QtCore.QSize(0, 0))
        IDLSanalyzer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(IDLSanalyzer)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 280))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_load = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load.sizePolicy().hasHeightForWidth())
        self.pushButton_load.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_2.addWidget(self.pushButton_load)
        self.pushButton_set = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set.sizePolicy().hasHeightForWidth())
        self.pushButton_set.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_set.setFont(font)
        self.pushButton_set.setObjectName("pushButton_set")
        self.horizontalLayout_2.addWidget(self.pushButton_set)
        self.pushButton_del = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_del.sizePolicy().hasHeightForWidth())
        self.pushButton_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setObjectName("pushButton_del")
        self.horizontalLayout_2.addWidget(self.pushButton_del)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.listWidget_data = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_data.sizePolicy().hasHeightForWidth())
        self.listWidget_data.setSizePolicy(sizePolicy)
        self.listWidget_data.setObjectName("listWidget_data")
        self.verticalLayout_3.addWidget(self.listWidget_data)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_expdata = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_expdata.sizePolicy().hasHeightForWidth())
        self.pushButton_expdata.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_expdata.setFont(font)
        self.pushButton_expdata.setObjectName("pushButton_expdata")
        self.horizontalLayout_3.addWidget(self.pushButton_expdata)
        self.pushButton_data2plot = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_data2plot.sizePolicy().hasHeightForWidth())
        self.pushButton_data2plot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_data2plot.setFont(font)
        self.pushButton_data2plot.setObjectName("pushButton_data2plot")
        self.horizontalLayout_3.addWidget(self.pushButton_data2plot)
        self.pushButton_data2fit = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_data2fit.sizePolicy().hasHeightForWidth())
        self.pushButton_data2fit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_data2fit.setFont(font)
        self.pushButton_data2fit.setObjectName("pushButton_data2fit")
        self.horizontalLayout_3.addWidget(self.pushButton_data2fit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 280))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_corp = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_corp.sizePolicy().hasHeightForWidth())
        self.pushButton_corp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_corp.setFont(font)
        self.pushButton_corp.setObjectName("pushButton_corp")
        self.verticalLayout_8.addWidget(self.pushButton_corp)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_croplow = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_croplow.sizePolicy().hasHeightForWidth())
        self.lineEdit_croplow.setSizePolicy(sizePolicy)
        self.lineEdit_croplow.setObjectName("lineEdit_croplow")
        self.horizontalLayout_5.addWidget(self.lineEdit_croplow)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_crophigh = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_crophigh.sizePolicy().hasHeightForWidth())
        self.lineEdit_crophigh.setSizePolicy(sizePolicy)
        self.lineEdit_crophigh.setObjectName("lineEdit_crophigh")
        self.horizontalLayout_5.addWidget(self.lineEdit_crophigh)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_corpconfirm = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_corpconfirm.sizePolicy().hasHeightForWidth())
        self.pushButton_corpconfirm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_corpconfirm.setFont(font)
        self.pushButton_corpconfirm.setObjectName("pushButton_corpconfirm")
        self.horizontalLayout_7.addWidget(self.pushButton_corpconfirm)
        self.pushButton_corpcancel = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_corpcancel.sizePolicy().hasHeightForWidth())
        self.pushButton_corpcancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_corpcancel.setFont(font)
        self.pushButton_corpcancel.setObjectName("pushButton_corpcancel")
        self.horizontalLayout_7.addWidget(self.pushButton_corpcancel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.pushButton_intcorrect = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_intcorrect.sizePolicy().hasHeightForWidth())
        self.pushButton_intcorrect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_intcorrect.setFont(font)
        self.pushButton_intcorrect.setObjectName("pushButton_intcorrect")
        self.verticalLayout_8.addWidget(self.pushButton_intcorrect)
        self.pushButton_sub2data = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sub2data.sizePolicy().hasHeightForWidth())
        self.pushButton_sub2data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_sub2data.setFont(font)
        self.pushButton_sub2data.setObjectName("pushButton_sub2data")
        self.verticalLayout_8.addWidget(self.pushButton_sub2data)
        self.pushButton_mergetwo = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mergetwo.sizePolicy().hasHeightForWidth())
        self.pushButton_mergetwo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_mergetwo.setFont(font)
        self.pushButton_mergetwo.setObjectName("pushButton_mergetwo")
        self.verticalLayout_8.addWidget(self.pushButton_mergetwo)
        self.pushButton_sub2data.raise_()
        self.pushButton_corp.raise_()
        self.pushButton_intcorrect.raise_()
        self.pushButton_mergetwo.raise_()
        self.groupBox.raise_()
        self.groupBox.raise_()
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 280))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_delanalysis = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delanalysis.sizePolicy().hasHeightForWidth())
        self.pushButton_delanalysis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_delanalysis.setFont(font)
        self.pushButton_delanalysis.setObjectName("pushButton_delanalysis")
        self.horizontalLayout_12.addWidget(self.pushButton_delanalysis)
        self.pushButton_viewset = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_viewset.sizePolicy().hasHeightForWidth())
        self.pushButton_viewset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_viewset.setFont(font)
        self.pushButton_viewset.setObjectName("pushButton_viewset")
        self.horizontalLayout_12.addWidget(self.pushButton_viewset)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.listWidget_analysis = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_analysis.sizePolicy().hasHeightForWidth())
        self.listWidget_analysis.setSizePolicy(sizePolicy)
        self.listWidget_analysis.setObjectName("listWidget_analysis")
        self.verticalLayout_7.addWidget(self.listWidget_analysis)
        self.pushButton_Analysis = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Analysis.sizePolicy().hasHeightForWidth())
        self.pushButton_Analysis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_Analysis.setFont(font)
        self.pushButton_Analysis.setObjectName("pushButton_Analysis")
        self.verticalLayout_7.addWidget(self.pushButton_Analysis)
        self.listWidget_analysis.raise_()
        self.groupBox_3.raise_()
        self.pushButton_Analysis.raise_()
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_plotwhat = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_plotwhat.sizePolicy().hasHeightForWidth())
        self.comboBox_plotwhat.setSizePolicy(sizePolicy)
        self.comboBox_plotwhat.setMinimumSize(QtCore.QSize(220, 0))
        self.comboBox_plotwhat.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.comboBox_plotwhat.setFont(font)
        self.comboBox_plotwhat.setObjectName("comboBox_plotwhat")
        self.comboBox_plotwhat.addItem("")
        self.comboBox_plotwhat.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_plotwhat)
        self.listWidget_plotlist = QtWidgets.QListWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_plotlist.sizePolicy().hasHeightForWidth())
        self.listWidget_plotlist.setSizePolicy(sizePolicy)
        self.listWidget_plotlist.setMaximumSize(QtCore.QSize(220, 16777215))
        self.listWidget_plotlist.setObjectName("listWidget_plotlist")
        self.verticalLayout_4.addWidget(self.listWidget_plotlist)
        self.pushButton_delplot = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delplot.sizePolicy().hasHeightForWidth())
        self.pushButton_delplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.pushButton_delplot.setFont(font)
        self.pushButton_delplot.setObjectName("pushButton_delplot")
        self.verticalLayout_4.addWidget(self.pushButton_delplot)
        self.comboBox_plotinverse = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_plotinverse.sizePolicy().hasHeightForWidth())
        self.comboBox_plotinverse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.comboBox_plotinverse.setFont(font)
        self.comboBox_plotinverse.setObjectName("comboBox_plotinverse")
        self.comboBox_plotinverse.addItem("")
        self.comboBox_plotinverse.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_plotinverse)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        IDLSanalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IDLSanalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        IDLSanalyzer.setMenuBar(self.menubar)
        self.action1 = QtWidgets.QAction(IDLSanalyzer)
        self.action1.setObjectName("action1")
        self.action1_2 = QtWidgets.QAction(IDLSanalyzer)
        self.action1_2.setObjectName("action1_2")
        self.action1_3 = QtWidgets.QAction(IDLSanalyzer)
        self.action1_3.setObjectName("action1_3")

        self.retranslateUi(IDLSanalyzer)
        QtCore.QMetaObject.connectSlotsByName(IDLSanalyzer)

    def retranslateUi(self, IDLSanalyzer):
        _translate = QtCore.QCoreApplication.translate
        IDLSanalyzer.setWindowTitle(_translate("IDLSanalyzer", "IDLS analyzer"))
        self.groupBox.setTitle(_translate("IDLSanalyzer", "Raw Data input"))
        self.pushButton_load.setText(_translate("IDLSanalyzer", "Load"))
        self.pushButton_set.setText(_translate("IDLSanalyzer", "Set"))
        self.pushButton_del.setText(_translate("IDLSanalyzer", "Delete"))
        self.pushButton_expdata.setText(_translate("IDLSanalyzer", "Export"))
        self.pushButton_data2plot.setText(_translate("IDLSanalyzer", "Add to plot"))
        self.pushButton_data2fit.setText(_translate("IDLSanalyzer", "Add to analysis"))
        self.groupBox_3.setTitle(_translate("IDLSanalyzer", "Data pre-process"))
        self.pushButton_corp.setText(_translate("IDLSanalyzer", "Crop preview"))
        self.label_4.setText(_translate("IDLSanalyzer", "from"))
        self.label_5.setText(_translate("IDLSanalyzer", "to"))
        self.label_6.setText(_translate("IDLSanalyzer", "cm-3"))
        self.pushButton_corpconfirm.setText(_translate("IDLSanalyzer", "Crop confirm"))
        self.pushButton_corpcancel.setText(_translate("IDLSanalyzer", "Crop cancel"))
        self.pushButton_intcorrect.setText(_translate("IDLSanalyzer", "Intrinsic correction"))
        self.pushButton_sub2data.setText(_translate("IDLSanalyzer", "Subtraction from two"))
        self.pushButton_mergetwo.setText(_translate("IDLSanalyzer", "Merge two"))
        self.groupBox_2.setTitle(_translate("IDLSanalyzer", "Data to analysis"))
        self.pushButton_delanalysis.setText(_translate("IDLSanalyzer", "Remove"))
        self.pushButton_viewset.setText(_translate("IDLSanalyzer", "View setting"))
        self.pushButton_Analysis.setText(_translate("IDLSanalyzer", "Start\n"
" Analysis!"))
        self.groupBox_5.setTitle(_translate("IDLSanalyzer", "Plot Raw data"))
        self.comboBox_plotwhat.setItemText(0, _translate("IDLSanalyzer", "Plot selected"))
        self.comboBox_plotwhat.setItemText(1, _translate("IDLSanalyzer", "Plot all data to be analyzed"))
        self.pushButton_delplot.setText(_translate("IDLSanalyzer", "Remove"))
        self.comboBox_plotinverse.setItemText(0, _translate("IDLSanalyzer", "Lifetime"))
        self.comboBox_plotinverse.setItemText(1, _translate("IDLSanalyzer", "Inverse Lifetime"))
        self.action1.setText(_translate("IDLSanalyzer", "1"))
        self.action1_2.setText(_translate("IDLSanalyzer", "1"))
        self.action1_3.setText(_translate("IDLSanalyzer", "1"))

